os: linux
dist: bionic
name: Emerald Run
language: python
python: 3.7
addons:
  apt:
    update: true
    packages:
      - gnuplot
before_script: pip3 install -r requirements.txt
script:
  - python3 setup.py flake8
  - python3 setup.py run
